version: '3.1'

services:
  mongodb:
    image: mongo:3.4.2
    restart: always
    ports:
      - 27017:27017
    expose:
      - '27017'
    volumes:
      - ./data/mongo:/data/db

  app:
    build: .
    restart: always
    ports:
      - 1984:1984
    environment:
      PORT: 1984
      MONGODB_URI: mongodb://mongodb:27017/interview_challenge
    links:
      - mongodb
    depends_on:
      - mongodb